plugins {
    id "com.android.application"
    id "org.jetbrains.kotlin.android"
}

android {
    namespace "app.prime.q2i"
    compileSdk 34

    defaultConfig {
        applicationId "app.prime.q2i"
        minSdk 21
        targetSdk 34
        versionCode 10
        versionName "10.0"
    }

    buildFeatures {
        aidl true
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    implementation "androidx.appcompat:appcompat:1.7.0"
}
